import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const envDir = join(root, 'src/environments');

const REQUIRED_VARS = [
  'FIREBASE_API_KEY',
  'FIREBASE_AUTH_DOMAIN',
  'FIREBASE_PROJECT_ID',
  'FIREBASE_STORAGE_BUCKET',
  'FIREBASE_MESSAGING_SENDER_ID',
  'FIREBASE_APP_ID',
];

function loadEnvFile(path) {
  const content = readFileSync(path, 'utf8');
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;

    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();

    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    if (!process.env[key]) {
      process.env[key] = value;
    }
  }
}

function getVar(name) {
  const value = process.env[name];
  if (!value) {
    console.error(`Missing required environment variable: ${name}`);
    console.error('');
    console.error('Local setup:');
    console.error('  1. vercel env pull .env.local');
    console.error('  2. npm start');
    console.error('');
    console.error('Or copy src/environments/environment.example.ts manually.');
    process.exit(1);
  }
  return value;
}

function generateFile(production) {
  const firebase = {
    apiKey: getVar('FIREBASE_API_KEY'),
    authDomain: getVar('FIREBASE_AUTH_DOMAIN'),
    projectId: getVar('FIREBASE_PROJECT_ID'),
    storageBucket: getVar('FIREBASE_STORAGE_BUCKET'),
    messagingSenderId: getVar('FIREBASE_MESSAGING_SENDER_ID'),
    appId: getVar('FIREBASE_APP_ID'),
  };

  return `// Auto-generated by scripts/generate-env.mjs — do not edit manually.
export const environment = {
  production: ${production},
  firebase: {
    apiKey: ${JSON.stringify(firebase.apiKey)},
    authDomain: ${JSON.stringify(firebase.authDomain)},
    projectId: ${JSON.stringify(firebase.projectId)},
    storageBucket: ${JSON.stringify(firebase.storageBucket)},
    messagingSenderId: ${JSON.stringify(firebase.messagingSenderId)},
    appId: ${JSON.stringify(firebase.appId)},
  },
};
`;
}

const envLocalPath = join(root, '.env.local');
if (existsSync(envLocalPath)) {
  loadEnvFile(envLocalPath);
}

if (!existsSync(envDir)) {
  mkdirSync(envDir, { recursive: true });
}

writeFileSync(join(envDir, 'environment.ts'), generateFile(false));
writeFileSync(join(envDir, 'environment.prod.ts'), generateFile(true));

console.log('Generated src/environments/environment.ts and environment.prod.ts');
